

export const ALL_SUBJECTS = [
  {
    id: "maths",
    name: "Maths",
    icon: "📐",
    accent: "#0ea5e9",
    light: "#f0f9ff",
    mid: "#e0f2fe",
    dk: "#0c4a6e",
  },
  {
    id: "eng-lang",
    name: "English Language",
    icon: "✍️",
    accent: "#f59e0b",
    light: "#fffbeb",
    mid: "#fef3c7",
    dk: "#78350f",
  },
  {
    id: "eng-lit",
    name: "English Literature",
    icon: "📖",
    accent: "#ec4899",
    light: "#fdf2f8",
    mid: "#fce7f3",
    dk: "#831843",
  },
  {
    id: "bio",
    name: "Biology",
    icon: "🧬",
    accent: "#10b981",
    light: "#ecfdf5",
    mid: "#d1fae5",
    dk: "#065f46",
  },

  {
    id: "chem",
    name: "Chemistry",
    icon: "🧪",
    accent: "#3b82f6",
    light: "#eff6ff",
    mid: "#dbeafe",
    dk: "#1e3a5f",
  },
  {
    id: "phys",
    name: "Physics",
    icon: "⚛️",
    accent: "#8b5cf6",
    light: "#f5f3ff",
    mid: "#ede9fe",
    dk: "#3b0764",
  },
  {
    id: "combined-sci",
    name: "Combined Science",
    icon: "🔬",
    accent: "#14b8a6",
    light: "#f0fdfa",
    mid: "#ccfbf1",
    dk: "#134e4a",
  },
  {
    id: "history",
    name: "History",
    icon: "🏛️",
    accent: "#d97706",
    light: "#fffbeb",
    mid: "#fef3c7",
    dk: "#78350f",
  },
  {
    id: "geography",
    name: "Geography",
    icon: "🌍",
    accent: "#16a34a",
    light: "#f0fdf4",
    mid: "#dcfce7",
    dk: "#14532d",
  },
  {
    id: "french",
    name: "French",
    icon: "🇫🇷",
    accent: "#2563eb",
    light: "#eff6ff",
    mid: "#dbeafe",
    dk: "#1e3a5f",
  },
  {
    id: "spanish",
    name: "Spanish",
    icon: "🇪🇸",
    accent: "#dc2626",
    light: "#fef2f2",
    mid: "#fee2e2",
    dk: "#7f1d1d",
  },
  {
    id: "german",
    name: "German",
    icon: "🇩🇪",
    accent: "#ef4444",
    light: "#fef2f2",
    mid: "#fee2e2",
    dk: "#991b1b",
  },
  {
    id: "business",
    name: "Business",
    icon: "💼",
    accent: "#0891b2",
    light: "#ecfeff",
    mid: "#cffafe",
    dk: "#164e63",
  },
  {
    id: "computing",
    name: "Computing",
    icon: "💻",
    accent: "#6366f1",
    light: "#eef2ff",
    mid: "#e0e7ff",
    dk: "#312e81",
  },
  {
    id: "dt",
    name: "Design & Technology",
    icon: "🛠️",
    accent: "#ea580c",
    light: "#fff7ed",
    mid: "#ffedd5",
    dk: "#7c2d12",
  },
  {
    id: "drama",
    name: "Drama",
    icon: "🎭",
    accent: "#a855f7",
    light: "#faf5ff",
    mid: "#f3e8ff",
    dk: "#581c87",
  },
  {
    id: "music",
    name: "Music",
    icon: "🎵",
    accent: "#f43f5e",
    light: "#fff1f2",
    mid: "#ffe4e6",
    dk: "#881337",
  },
  {
    id: "politics",
    name: "Politics",
    icon: "🗳️",
    accent: "#0f766e",
    light: "#f0fdfa",
    mid: "#ccfbf1",
    dk: "#134e4a",
    _politics: true,
  },
];
